build:
  apt:
    packages:
      - build-essential
      - python3-dev
      - libatlas-base-dev
      - gfortran
      - libpq-dev
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libjpeg-dev
      - libfreetype6-dev
      - pkg-config
