name: Keep Alive

on:
  schedule:
    # Run every 2 minutes (GitHub Actions minimum interval)
    - cron: "*/2 * * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Endpoint
        run: |
          curl -f https://your-app-name.onrender.com/health || echo "Health check failed"
        env:
          # Add your app URL as a secret in GitHub repository settings
          APP_URL: ${{ secrets.APP_URL }}
